services:

  postgres:
    image: postgres
    container_name: mypostgres
    ports:
      - 5433:5432
    networks:
      - webnotesnet
    env_file:
      - .env
    volumes:
      - webnotes-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d mydatabase -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  webnotes:
    image: webnotes
    container_name: webnotes-container
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - webnotesnet

networks:
  webnotesnet:
    name: webnotesnet

volumes:
  webnotes-volume: